### ISSUE TITLE
Availability of AlphaCode

### ISSUE THREAD

**Issue by jstan15** [deepmind/code_contests#13]
Hi,
I am fascinated by the results from your paper and I was wondering whether there is a way for us to test AlphaCode ourselves. Is AlphaCode available to the public for testing?

Thank you.

**Comment by davidhchoi** [comment]
Unfortunately the only public code we have released is in the this repository: the dataset, code for loading it, and code for evaluating submissions. Most of our system is too tied with internal infrastructure to make it publicly available (e.g. tools for running on distributed TPUs), but given a large-scale transformer implementation you should be able to follow the methods provided in the paper to try to reproduce AlphaCode.

Feel free to ask any questions about the paper, or if things aren't clear there.
