### ISSUE TITLE
Does anyone know what Segmentation fault means ?

### ISSUE THREAD

**Issue by yefangwong** [deepmind/code_contests#15]
I execute bazel command on my computer :

bazel run -c opt execution:solve_example --   --valid_path=/tmp/dm-code_contests/code_contests_valid.riegeli   --python3_path=/usr/bin/python3 --python3_library_paths=/usr/lib/python3

Then I got Segmentation fault, Something wrong right? 

I had already use gsutil to download code contests dataset, My OS is Ubuntu 18.04 on Windows 11.

Any ideas ?

Thanks

**Comment by jtkeeling** [comment]
Hello - do you see any other logs/output, or just a segfault? Did the code successfully compile, but then fail to run?

**Comment by felixgimeno** [comment]
Closing this as I cannot reproduce.
