### ISSUE TITLE
Failed: Gregor and Cryptography problem not found. Did you pass the validation dataset?

### ISSUE THREAD

**Issue by wvaughn409** [deepmind/code_contests#17]
***UPDATE:  I see now that the first command in the section "Executing and evaluating solutions" seems to be expected to fail, because running the subsequent command:

`bazel run -c opt execution:solve_example -- \
  --valid_path=/tmp/dm-code_contests/code_contests_valid.riegeli \
  --python3_path=/usr/bin/python3.10 --python3_library_paths=/usr/lib/python3.10`

...which specifies the Python version does attempt to solve the "Gregor and Cryptography" problem. It would have been very helpful if the instructions would have called out this expectation of an initial failure like "...demonstrates this functionality, and can be run with e.g., _but this is expected to fail because of the need to specify a particular python version for certain problems. i.e. you should see 'Failed: Gregor and Cryptography problem not found. Did you pass the validation dataset?'_ "

That could have been explained better. Additionally, I had to jump through a few more hoops to get Python 3.10 installed on Ubuntu before that second command would work. I followed some instructions on this page https://computingforgeeks.com/how-to-install-python-on-ubuntu-linux-system/
...but had some errors with that which required updating certificates using:
sudo apt-get install --reinstall ca-certificates
...and even after that had to try several times the last step on that page^^ because kept getting gpg key errors. finally worked and i was able to run the line that performs the solving of "Gregor and Cryptography"

`bazel run -c opt execution:solve_example -- \
  --valid_path=/tmp/dm-code_contests/code_contests_valid.riegeli \
  --python3_path=/usr/bin/python3.10 --python3_library_paths=/usr/lib/python3.10`

...successfully.  Now will someone please explain how to use this at work so I can just write a program that does my job for me and just keep an eye on my laptop while I sit on a beach this summer?  ;)

----------------------------------------------------------------------------------------------------------------------------

I thought initially that this problem was native to LaudemPax's Docker image, which I was using on Windows 11 environment to try this out, but I switched over to Ubuntu and got so far as to get a good output from this command:

bazel run -c opt :print_names_and_sources /tmp/dm-code_contests/code_contests_valid.riegeli

...which returns a long list of code problems after compiling (see further down this post), but when I then execute the first example command under "Executing and evaluating solutions"...

`bazel run -c opt execution:solve_example -- \
  /tmp/dm-code_contests/code_contests_valid.riegeli`

...I get the following error:

`Failed: Gregor and Cryptography problem not found. Did you pass the validation dataset?
`
Please advise.
-----------------------------------------------------------------------------

`
CODEFORCES 1548_C. The Three Little Pigs
CODEFORCES 1548_D1. Gregor and the Odd Cows (Easy)
CODEFORCES 1548_D2. Gregor and the Odd Cows (Hard)
CODEFORCES 1548_E. Gregor and the Two Painters
CODEFORCES 1549_A. Gregor and Cryptography
CODEFORCES 1549_B. Gregor and the Pawn Game
CODEFORCES 1549_C. Web of Lies
CODEFORCES 1549_D. Integers Have Friends
CODEFORCES 1551_A. Polycarp and Coins
CODEFORCES 1551_B1. Wonderful Coloring - 1
CODEFORCES 1551_B2. Wonderful Coloring - 2
CODEFORCES 1551_C. Interesting Story
CODEFORCES 1551_D1. Domino (easy version)
CODEFORCES 1551_D2. Domino (hard version)
CODEFORCES 1551_E. Fixed Points
CODEFORCES 1551_F. Equidistant Vertices
CODEFORCES 1552_A. Subsequence Permutation
CODEFORCES 1552_B. Running for Gold
CODEFORCES 1552_C. Maximize the Intersections
CODEFORCES 1552_D. Array Differentiation
CODEFORCES 1552_E. Colors and Intervals
CODEFORCES 1552_F. Telepanting
CODEFORCES 1552_G. A Serious Referee
CODEFORCES 1552_I. Organizing a Music Festival
CODEFORCES 1553_A. Digits Sum
CODEFORCES 1553_B. Reverse String
CODEFORCES 1553_C. Penalty
CODEFORCES 1553_D. Backspace
CODEFORCES 1553_E. Permutation Shift
CODEFORCES 1553_F. Pairwise Modulo
CODEFORCES 1553_G. Common Divisor Graph
CODEFORCES 1553_H. XOR and Distance
CODEFORCES 1553_I. Stairs
CODEFORCES 1554_A. Cherry
CODEFORCES 1554_B. Cobb
CODEFORCES 1554_C. Mikasa
CODEFORCES 1554_D. Diane
CODEFORCES 1554_E. You
CODEFORCES 1555_A. PizzaForces
CODEFORCES 1555_B. Two Tables
CODEFORCES 1555_C. Coin Rows
CODEFORCES 1555_D. Say No to Palindromes
CODEFORCES 1555_E. Boring Segments
CODEFORCES 1555_F. Good Graph
CODEFORCES 1556_A. A Variety of Operations
CODEFORCES 1556_B. Take Your Places!
CODEFORCES 1556_C. Compressed Bracket Sequence
CODEFORCES 1556_D. Take a Guess
CODEFORCES 1556_E. Equilibrium
CODEFORCES 1556_F. Sports Betting
CODEFORCES 1556_G. Gates to Another World
CODEFORCES 1556_H. DIY Tree
CODEFORCES 1557_A. Ezzat and Two Subsequences
CODEFORCES 1557_B. Moamen and k-subarrays
CODEFORCES 1557_C. Moamen and XOR
CODEFORCES 1557_D. Ezzat and Grid
CODEFORCES 1557_E. Assiut Chess
CODEFORCES 1558_C. Bottom-Tier Reversals
CODEFORCES 1558_D. Top-Notch Insertions
CODEFORCES 1558_E. Down Below
CODEFORCES 1559_A. Mocha and Math
CODEFORCES 1559_B. Mocha and Red and Blue
CODEFORCES 1559_C. Mocha and Hiking
CODEFORCES 1559_D1. Mocha and Diana (Easy Version)
CODEFORCES 1559_D2. Mocha and Diana (Hard Version)
CODEFORCES 1559_E. Mocha and Stars
CODEFORCES 1560_A. Dislike of Threes
CODEFORCES 1560_B. Who's Opposite?
CODEFORCES 1560_C. Infinity Table
CODEFORCES 1560_D. Make a Power of Two
CODEFORCES 1560_E. Polycarp and String Transformation
CODEFORCES 1560_F1. Nearest Beautiful Number (easy version)
CODEFORCES 1560_F2. Nearest Beautiful Number (hard version)
CODEFORCES 1561_A. Simply Strange Sort
CODEFORCES 1561_B. Charmed by the Game
CODEFORCES 1561_C. Deep Down Below
CODEFORCES 1561_D1. Up the Strip (simplified version)
CODEFORCES 1561_D2. Up the Strip
CODEFORCES 1562_A. The Miracle and the Sleeper
CODEFORCES 1562_B. Scenes From a Memory
CODEFORCES 1562_C. Rings
CODEFORCES 1562_D1. Two Hundred Twenty One (easy version)
CODEFORCES 1562_D2. Two Hundred Twenty One (hard version)
CODEFORCES 1562_E. Rescue Niwen!
CODEFORCES 1566_A. Median Maximization
CODEFORCES 1566_B. MIN-MEX Cut
CODEFORCES 1566_C. MAX-MEX Cut
CODEFORCES 1566_D1. Seating Arrangements (easy version)
CODEFORCES 1566_D2. Seating Arrangements (hard version)
CODEFORCES 1566_E. Buds Re-hanging
CODEFORCES 1566_F. Points Movement
CODEFORCES 1566_G. Four Vertices
CODEFORCES 1566_H. Xor-quiz
CODEFORCES 1567_B. MEXor Mixup
CODEFORCES 1567_C. Carrying Conundrum
CODEFORCES 1567_D. Expression Evaluation Error
CODEFORCES 1567_E. Non-Decreasing Dilemma
CODEFORCES 1567_F. One-Four Overload
CODEFORCES 1569_A. Balanced Substring
CODEFORCES 1569_B. Chess Tournament
CODEFORCES 1569_C. Jury Meeting
CODEFORCES 1569_D. Inconvenient Pairs
CODEFORCES 1569_E. Playoff Restoration
CODEFORCES 1569_F. Palindromic Hamiltonian Path
CODEFORCES 1572_B. Xor of 3
CODEFORCES 1572_C. Paint
CODEFORCES 1572_D. Bridge Club
CODEFORCES 1572_E. Polygon
CODEFORCES 1572_F. Stations
CODEFORCES 1573_A. Countdown
CODEFORCES 1573_C. Book
CODEFORCES 1574_A. Regular Bracket Sequences
CODEFORCES 1574_B. Combinatorics Homework
CODEFORCES 1574_C. Slay the Dragon
CODEFORCES 1574_D. The Strongest Build
CODEFORCES 1574_E. Coloring
CODEFORCES 1574_F. Occurrences
`

**Comment by wvaughn409** [comment]
Got this to work on an Ubuntu 20.04.4 LTS  virtual machine on Synology NAS. Had to install many dependencies that were not called out in the instructions, but finally got all the example commands to work (See first comment updates). Hope this helps someone. :)

**Comment by felixgimeno** [comment]
Sorry, the `valid_path` was a required flag but this was not properly documented, and the command in the README was lacking this. I will try to fix it.
