### ISSUE TITLE
License of data usage

### ISSUE THREAD

**Issue by lehougoogle** [deepmind/code_contests#28]
Hi the authors,

I want to use this data. In the "License" section, it reads:

```
The code is licensed under the [Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0).

All non-code materials provided are made available under the terms of the CC BY 4.0 license ([Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by/4.0/legalcode)).
```

The *data* that contains coding problems are "non-code materials", right? I assume that the Apache 2.0 Licensed code here is the code in this github repo, not the actual code *data*.

**Comment by jtkeeling** [comment]
Yes, this is the correct interpretation. Apologies for the somewhat confusing wording.
