### ISSUE TITLE
Dataset Unavailable

### ISSUE THREAD

**Issue by sankalpie** [deepmind/code_contests#35]
I have used the huggingFace API to fetch the dataset.

On 23 August 2023
When the api is fetched it returns the error: {"error":"The server is busier than usual and the response is not ready yet. Please retry later."}

Just a few days before today (around 15 August, 2023) the api worked perfectly without any errors.

I rely heavily on the availability of the dataset. It is critical that the server is back running in no time. 

When will the issue be fixed. If this is not the right place to post this issue, then where is the most appropriate place.

**Comment by felixgimeno** [comment]
The appropriate place is the huggingface API
