### ISSUE TITLE
Error downloading com_google_riegeli

### ISSUE THREAD

**Issue by Symbolk** [deepmind/code_contests#6]
Hi, it seems to be a network error since I am behind a system level proxy, should and how can I configure bazel to work with a proxy?

```
ERROR: An error occurred during the fetch of repository 'com_google_riegeli':

Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/google/riegeli/archive/587c7921700a58f53fbd2b47fcf9c6dc38477a32.tar.gz]
```

**Comment by davidhchoi** [comment]
I'm not sure exactly, and can't test it, but I think that there are more general instructions about how to use bazel with proxies that should hopefully work here, like [using `dist_dir`](https://stackoverflow.com/questions/52311486/bazel-build-behind-proxy) or [env variables](https://docs.bazel.build/versions/0.29.1/external.html#using-proxies). Do either of these work?

**Comment by Symbolk** [comment]
> 

Thanks for the response, I have tried env but it failed, but I successfully bypass this via working on Colab.
