### ISSUE TITLE
Print other features for each problem

### ISSUE THREAD

**Issue by arghavanmo** [deepmind/code_contests#8]
Hi,
Thank you for this great dataset. I have two questions:

1. How can we print the description of the problems and solutions (including correct, wrong, etc) and test cases? do you have any list of features that can help us to fetch other attributes?
2. for example "CODEFORCES 1569_A" as a source, means the problem is fetched from codeforces but what is 1569_A or_B? It seems more than an index to me.

Thank you :)

**Comment by KareemAlaa2001** [comment]
Not an author so don't have an exact answer, but check out this [tutorial](https://developers.google.com/protocol-buffers/docs/pythontutorial) if you haven't already, it outlines how to use proto2 files for simple I/O in python (and what the file contents actually mean!)

**Comment by arghavanmo** [comment]
Thank you, I will try.
